version: "3.7"
services:
  rest:
    image: go-rest-base
    build:
      context: .
      dockerfile: Dockerfile.debug
    # environment:
      # DEMO_REDIS: redis
    ports:
        - "3000:3000"
        - "2345:2345"
        - "8080:8080"
        - "5001:5001"
    security_opt:
        - "seccomp:unconfined"
    # Disable dlv for now 
    # command: /go/bin/dlv debug --headless --log --listen=:2345 --api-version=2
    volumes:
        - ./app:/go/src/app
  # redis:
  #   image: redis