# Use previous built base image
FROM app-api-base:latest

# Update and install apks
RUN apk --update add --no-cache git gcc musl-dev

# Install dlv for VSCode debugger
RUN go get github.com/go-delve/delve/cmd/dlv

# Disable Go Module due to an issue with realize
ENV GO111MODULE=off

# Install realize
RUN go get github.com/oxequa/realize

# Turn Go module back on
ENV GO111MODULE=on

RUN go mod download

# EXPOSE port for debugger
EXPOSE 2345

CMD ["realize", "start"]
