version: "3.3"

services:
  api:
    image: app-api-base
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 8080:8080
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"